Add test for user permissions
team-datong/Datong pull request #36
Opened 2016-11-10 08:26 UTC by kgieseking

Added some tests for user permissions and user auth, changed a few step definitions to reflect these tests.

2016-11-10 08:32 UTC, susannasouv commented on features/step_definitions/user_auth_steps.rb
> +<<<<<<< HEAD
This needs to be removed

2016-11-10 08:34 UTC, susannasouv commented on features/user_permissions.feature
> +<<<<<<< HEAD
This should also be removed

2016-11-10 09:21 UTC, susannasouv requested changes
Remove the [file_name].swp files; that's a sign that you were in middle of editing those files elsewhere and didn't save so you might want to check on those...

2016-11-12 09:33 UTC, jeremyjpark commented
You might also want to clean up your commit history so that in the end it looks more concise. I can work on the rebasing with you.

2016-11-17 07:08 UTC, susannasouv approved these changes

2016-11-17 19:04 UTC, aganpule approved these changes

2016-11-17 21:11 UTC, merged